import type { DbProject } from '@/types/database';

export const DEMO_PROJECTS: DbProject[] = [
  {
    id: 'p-1',
    created_at: '2026-05-01T10:00:00Z',
    owner_id: 'user-demo-1',
    title: 'AI Study Buddy',
    dept: 'Machine Learning',
    description: 'AI-powered study companion with adaptive learning pathways, real-time quiz generation, and collaborative note synthesis across class cohorts.',
    tech: ['React', 'Python', 'TensorFlow', 'FastAPI', 'PostgreSQL'],
    open_roles: [
      { title: 'ML Engineer', skills: ['Python', 'PyTorch', 'Transformers'], count: 2 },
      { title: 'Frontend Developer', skills: ['React', 'TypeScript', 'Tailwind'], count: 1 },
      { title: 'UI/UX Researcher', skills: ['Figma', 'User Testing'], count: 1 },
    ],
    image_url: null,
    difficulty: 'Intermediate',
    duration: '3 months',
    deadline: '2026-06-01',
    team_size_capacity: 5,
    is_public: true,
  },
  {
    id: 'p-2',
    created_at: '2026-05-03T14:30:00Z',
    owner_id: 'user-demo-2',
    title: 'Smart Campus Nav',
    dept: 'Engineering + Design',
    description: 'IoT-driven campus navigation and resource management system showing real-time study room occupancy, wheelchair accessible paths, and bus tracking.',
    tech: ['React Native', 'Node.js', 'IoT', 'MQTT', 'Mapbox'],
    open_roles: [
      { title: 'IoT Firmware Dev', skills: ['ESP32', 'C++', 'MQTT'], count: 2 },
      { title: 'Mobile Dev', skills: ['React Native', 'TypeScript'], count: 1 },
    ],
    image_url: null,
    difficulty: 'Intermediate',
    duration: '4 months',
    deadline: '2026-06-15',
    team_size_capacity: 4,
    is_public: true,
  },
  {
    id: 'p-3',
    created_at: '2026-05-05T09:15:00Z',
    owner_id: 'user-demo-3',
    title: 'EcoTracker Campus',
    dept: 'Sustainability',
    description: 'Gamified carbon footprint tracking for student housing and dining halls, rewarding eco-conscious choices with campus store credits.',
    tech: ['Next.js', 'Python', 'FastAPI', 'TailwindCSS'],
    open_roles: [
      { title: 'Full Stack Dev', skills: ['Next.js', 'PostgreSQL'], count: 1 },
      { title: 'Data Analyst', skills: ['Pandas', 'Visualization'], count: 1 },
    ],
    image_url: null,
    difficulty: 'Beginner',
    duration: '2 months',
    deadline: '2026-07-01',
    team_size_capacity: 4,
    is_public: true,
  },
  {
    id: 'p-4',
    created_at: '2026-05-08T16:45:00Z',
    owner_id: 'user-demo-4',
    title: 'CrossThink Core',
    dept: 'Machine Learning',
    description: 'Decentralized collaboration engine matching students, researchers, and mentors using semantic embeddings and mutual availability graphs.',
    tech: ['React', 'TypeScript', 'Next.js', 'PostgreSQL', 'TailwindCSS'],
    open_roles: [
      { title: 'Backend Architect', skills: ['Node.js', 'PostgreSQL', 'Redis'], count: 1 },
      { title: 'AI Matching Specialist', skills: ['Vector DBs', 'Embeddings'], count: 1 },
    ],
    image_url: null,
    difficulty: 'Advanced',
    duration: '6 months',
    deadline: '2026-08-30',
    team_size_capacity: 6,
    is_public: true,
  },
  {
    id: 'p-5',
    created_at: '2026-05-10T11:00:00Z',
    owner_id: 'user-demo-5',
    title: 'Campus Micro-Grants Ledger',
    dept: 'FinTech',
    description: 'Transparent micro-grant and club crowdfunding platform with escrow milestones and student voting governance.',
    tech: ['Solidity', 'Next.js', 'PostgreSQL', 'TailwindCSS'],
    open_roles: [
      { title: 'Smart Contract Auditor', skills: ['Solidity', 'Foundry'], count: 1 },
      { title: 'Frontend Engineer', skills: ['React', 'Web3.js'], count: 2 },
    ],
    image_url: null,
    difficulty: 'Advanced',
    duration: '3 months',
    deadline: '2026-07-15',
    team_size_capacity: 5,
    is_public: true,
  },
  {
    id: 'p-6',
    created_at: '2026-05-12T13:20:00Z',
    owner_id: 'user-demo-6',
    title: 'HoloLab XR Biology',
    dept: 'XR / Immersive',
    description: 'Interactive WebXR anatomical anatomy models and virtual lab simulations for remote biology students.',
    tech: ['Three.js', 'WebXR', 'Blender', 'TypeScript'],
    open_roles: [
      { title: '3D Technical Artist', skills: ['Blender', 'glTF', 'Shaders'], count: 1 },
      { title: 'WebXR Specialist', skills: ['Three.js', 'WebGL'], count: 2 },
    ],
    image_url: null,
    difficulty: 'Advanced',
    duration: '4 months',
    deadline: '2026-09-01',
    team_size_capacity: 4,
    is_public: true,
  }
];
